import type { Metadata } from "next";
import "./globals.css";
import { fontValela } from "@/fonts";
import { ReactQueryProvider } from "@/components/query-provider";
/* import dayjs from "dayjs"; */
/* import 'dayjs/locale/pt-br' */
/* dayjs.locale("pt-br"); */

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <html lang="pt-br">
        <body className={`${fontValela}`}>{children}</body>
      </html>
    </ReactQueryProvider>
  );
}
