
@HOST=http://localhost:9000

# @name login
POST {{HOST}}/auth
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "example"
}

###
# @name register
POST {{HOST}}/users
Content-Type: application/json

{
    "name": "example",
    "email": "example@gmail.com",
    "password": "example",
    "nickname": "mari.mari"
}